version: 0.2

env:
  variables:
    CHROME_PATH: /usr/bin/google-chrome
    CI: '1'
    ONLY_WEB: '1'

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Instalando dependencias del sistema (Chrome)..."
      - apt-get update -qq
      - apt-get install -y -qq wget unzip xvfb
      - wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - apt install -qq -y ./google-chrome-stable_current_amd64.deb || apt -qq --fix-broken install -y
      - google-chrome --version
      - echo "Instalando dependencias de Kraken..."
      - npm install
      - echo "Compilando Kraken..."
      - npm run build
      - cd examples/kraken-demo
      - echo "Instalando dependencias de aplicación..."
      - npm install

  build:
    commands:
      - echo "Ejecutando pruebas..."
      - npm run test

artifacts:
  files:
